service: lambda-demo

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverless
  stage: dev
  region: us-west-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
